apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring3-app
  labels:
    app: spring3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring3
  template:
    metadata:
      labels:
        app: spring3
    spec:
      containers:
      - name: spring3-web-app
        image: mashood6106/spring3:v1
        ports:
        - containerPort: 8080

