apiVersion: v1
kind: Service
metadata:
  name: spring3-service
  labels:
    app: spring3
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30123
    protocol: TCP
  selector:
    app: spring3                              # Label selector

