name: Build and Deploy Java App to Tomcat

on:
  push:
    branches:
      - master  
  pull_request:
    branches:
      - master  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout code
        uses: actions/checkout@v3

      
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adoptopenjdk'
		
      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven
	  

      - name: Build with Maven
        run: mvn clean package 

      - name: Deploy to Tomcat
        run: |
          curl -u $TOMCAT_USER:$TOMCAT_PASSWORD \
               -T target/spring3-mvc-maven-xml-hello-world-1.1.0.war \
               "http://$TOMCAT_HOST:$TOMCAT_PORT/manager/text/deploy?path=/spring3&update=true"

        env:
          TOMCAT_USER: ${{ secrets.TOMCAT_USER }}
          TOMCAT_PASSWORD: ${{ secrets.TOMCAT_PASSWORD }}
          TOMCAT_HOST: ${{ secrets.TOMCAT_HOST }}
          TOMCAT_PORT: ${{ secrets.TOMCAT_PORT }}

